CREATE SCHEMA IF NOT EXISTS bronze AUTHORIZATION olivier_picaud;
CREATE SCHEMA IF NOT EXISTS silver AUTHORIZATION olivier_picaud;
CREATE SCHEMA IF NOT EXISTS gold AUTHORIZATION olivier_picaud;
CREATE SCHEMA IF NOT EXISTS monitoring AUTHORIZATION olivier_picaud;
