CREATE SCHEMA IF NOT EXISTS bronze AUTHORIZATION co2_user;
CREATE SCHEMA IF NOT EXISTS silver AUTHORIZATION co2_user;
CREATE SCHEMA IF NOT EXISTS gold AUTHORIZATION co2_user;
CREATE SCHEMA IF NOT EXISTS monitoring AUTHORIZATION co2_user;
